spring.application.name=BackendProj
server.port=1974
server.servlet.context-path=/api
spring.datasource.url=jdbc:mysql://mysql-22969a82-raorajesh7700-31c1.g.aivencloud.com:28105/defaultdb?sslmode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_x_UlT0otJOA0Ma-cLgV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
