spring.application.name=BackendProj
server.port=${PORT:8080}
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://62.72.28.52:3306/u906063635_fst
spring.datasource.username=u906063635_fst
spring.datasource.password=#Y:+rf|8fX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect